#!/usr/bin/env python3

"""
Non-Conformance Test Case #16: Undefined Pseudo-Header Fields

Violates HTTP/3 specifications by sending a request containing 
undefined pseudo-header fields. The client MUST NOT generate 
pseudo-header fields other than those defined in the specification.
"""

import asyncio
import sys
import os

# Add the src directory to Python path
sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..', '..', 'src'))
sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..', 'shared'))

from utils import BaseTestClient, create_common_headers


class TestCase16Client(BaseTestClient):
    """Test Case 16: Request with undefined pseudo-header fields."""
    
    def __init__(self):
        super().__init__(
            test_case_id=16,
            test_name="Undefined pseudo-header fields",
            violation_description="Undefined pseudo-headers MUST NOT be generated by client",
            rfc_section="HTTP/3 Pseudo-Header Field Requirements"
        )
    
    async def _execute_test_logic(self, protocol):
        """Execute the specific test logic for Test Case 16."""
        
        # Step 1: Set up conformant HTTP/3 connection
        await self.setup_conformant_connection()
        
        # Step 2: Create request stream
        print("📍 Creating request stream")
        request_stream_id = self.create_request_stream(protocol)
        
        # Step 3: Send HEADERS frame with undefined pseudo-headers - VIOLATION!
        print("📍 Sending HEADERS frame with undefined pseudo-header fields")
        print("🚫 PROTOCOL VIOLATION: Undefined pseudo-headers MUST NOT be generated!")
        print("🚫 Expected error: Connection termination or header rejection")
        
        # Create headers with undefined pseudo-header fields
        # Valid pseudo-headers are: :method, :path, :scheme, :authority (for requests)
        # and :status (for responses). All others are forbidden.
        violation_headers = [
            # Valid pseudo-headers first
            (b":method", b"GET"),
            (b":path", b"/test-undefined-pseudo-headers"),
            (b":scheme", b"https"),
            (b":authority", b"test-server"),
            # FORBIDDEN undefined pseudo-headers
            (b":foo", b"bar"),  # FORBIDDEN - undefined pseudo-header
            (b":custom-header", b"test-value"),  # FORBIDDEN - undefined pseudo-header
            (b":version", b"1.0"),  # FORBIDDEN - undefined pseudo-header
            (b":protocol", b"http3"),  # FORBIDDEN - undefined pseudo-header
            (b":status", b"200"),  # FORBIDDEN - :status is for responses only, not requests
            (b":encoding", b"gzip"),  # FORBIDDEN - undefined pseudo-header
            # Regular headers
            (b"x-test-case", b"16"),
            (b"user-agent", b"HTTP3-NonConformance-Test/1.0"),
        ]
        
        try:
            self.h3_api.send_headers_frame(request_stream_id, violation_headers, end_stream=False)
            self.results.add_step("undefined_pseudo_headers_sent", True)
            print(f"✅ HEADERS frame with undefined pseudo-headers sent on stream {request_stream_id}")
            print(f"   └─ Headers: {len(violation_headers)} header fields")
            print(f"   └─ Undefined pseudo-headers: :foo, :custom-header, :version, :protocol, :status, :encoding")
            print(f"   └─ This violates HTTP/3 pseudo-header field restrictions!")
        except Exception as e:
            print(f"❌ Failed to send HEADERS frame: {e}")
            print("   └─ This may indicate the violation was caught early")
            self.results.add_step("undefined_pseudo_headers_sent", True)
            self.results.add_note(f"HEADERS frame sending failed: {str(e)}")
            return
        
        # Step 4: Attempt to send DATA frame (if headers were accepted)
        print("📍 Sending DATA frame with request body")
        request_body = b'{"message": "This request contains undefined pseudo-header fields"}'
        
        try:
            self.h3_api.send_data_frame(request_stream_id, request_body, end_stream=True)
            self.results.add_step("request_body_sent", True)
            print(f"✅ DATA frame sent on stream {request_stream_id}")
            print(f"   └─ Payload: {len(request_body)} bytes")
        except Exception as e:
            print(f"❌ Failed to send DATA frame: {e}")
            self.results.add_step("request_body_sent", False)
            self.results.add_note(f"DATA frame sending failed: {str(e)}")
        
        # Add test-specific observations
        self.results.add_note("Request sent with undefined pseudo-header fields (protocol violation)")
        self.results.add_note("Client MUST NOT generate pseudo-headers other than :method, :path, :scheme, :authority")
        self.results.add_note("Undefined pseudo-headers: :foo, :custom-header, :version, :protocol, :status, :encoding")


async def main():
    """Main entry point for Test Case 16."""
    test_client = TestCase16Client()
    await BaseTestClient.main(test_client)


if __name__ == "__main__":
    asyncio.run(main()) 